### ISSUE TITLE
TODO: 로그인 기능 추가 및 수정하기

### ISSUE THREAD

**Issue by ddolboghi** [4-ComehereTeam/ssg-client#52]
## 어떤 기능인가요?

- 소셜 로그인(간편회원 로그인) 시 accessToken 발급 받기
- 소셜 로그인 후 리다이렉트되는 페이지 변경하기
- 로그아웃 후 리다이렉트되는 페이지 변경하기

## 작업 상세 내용

- [x] 소셜 로그인 시 백엔드와 통신해서 accessToken 발급 받고 세션에 저장하기
- [x] #70
- [x] 로그아웃 후 로그인페이지로 리다이렉트하기
- [x] 로그인 시 휴면 여부 조회 API 통신 후 휴면 회원이면 본인인증 페이지로 리다이렉트하기

**Comment by ddolboghi** [comment]
#77 해결
