### ISSUE TITLE
TODO: 상품 상세 페이지 하단 버튼 구현하기

### ISSUE THREAD

**Issue by ddolboghi** [4-ComehereTeam/ssg-client#58]
## 어떤 기능인가요?

- 상품 상세 페이지 하단에 고정된 버튼

## 작업 상세 내용

- [x] 좋아요 버튼 구현
- [x] 구매하기 버튼 클릭 시 '장바구니' 버튼으로 대체

- [x] 옵션 선택 창 구현
    - [x] 윗 옵션 선택 안하고 밑 옵션 선택 못하게 막기
    - [x] 최하위 옵션 선택 창에서만 재고 보여주기
    - [x] 모든 옵션 선택 후 해당하는 옵션의 상품 정보 보여주기
    - [x] 상품 개수에따른 가격 보여주기
    - [x] 상품 개수 조절 상한선 = 해당 optionId의 stock값 --> 백엔드 api 수정 요청 필요
    - [x] 개수에 따른 총합계 변화
    - [x] 옵션이 없는 상품은 상품 카드만 보여주기
    - [x] 옵션창 높이 조절
    - [x] 옵션창 스크롤되게 하기
    - [x] #68

- [x] 바로구매 클릭 시 로그인 여부 판단
    - [x] 로그인했으면 주문페이지로 이동
    - [x] 로그인 안했으면 로그인 페이지로 이동
        - [x] #71

- [x] #69

## 참고할만한 자료(선택)
- 구매하기 버튼 클릭시
![image](https://github.com/ComehereTeam/ssg-client/assets/100576111/7cc41b11-ca3c-4582-8cb1-a8364a4a3fc8)

- 옵션이 있는 상품 
![image](https://github.com/ComehereTeam/ssg-client/assets/100576111/d65d8466-d5da-4a52-8623-e93dbf0a29e5)
![image](https://github.com/ComehereTeam/ssg-client/assets/100576111/3ddf379b-a986-4252-9224-14af7385d844)
![image](https://github.com/ComehereTeam/ssg-client/assets/100576111/fd61458a-d728-46f1-afaa-a1d1f8ae2ecd)

**Comment by ddolboghi** [comment]
#87을 마지막으로 구현 완료
