### ISSUE TITLE
TODO: 간편 회원가입 구현

### ISSUE THREAD

**Issue by ddolboghi** [4-ComehereTeam/ssg-client#63]
## 어떤 기능인가요?

- 간편 회원가입 구현하기

## 작업 상세 내용

- [x] 간편 회원가입 페이지 및 폼 만들기
- [x] 이메일 조회로 기존 회원 여부 판단하기
- [x] 간편 회원가입 API 통신하기

**Comment by ddolboghi** [comment]
#73 구현 완료!
